### ISSUE TITLE
`opt<-` ?

### ISSUE THREAD

**Issue by meztez** [dgkf/options#8]
I'm sure you thought about it.

Would it make senses to have a `opt<-` method?

What could it do over the regular `options` to make it a worthwhile addition?

Autocomplete options name?

I don't even know if it makes sense.

I'm thinking, maybe I could reexport it and use it like
```r
opt("port") <- 1234
```
It's the same as `options("mypackage.port" = 1234)`, minus the mypackage part.

**Comment by dgkf** [comment]
That's a cool idea! I don't think the thought crossed my mind.

There are a few syntactic niceties that I think would be worth exploring, and this feels like a good starting point.

What do you think should be returned? Generally, `fn<-` return the right-hand-side:

```r
x <- list(1, 2)
n <- names(x) <- c("a", "b")
n 
## [1] "a" "b"
```

But `options()` returns the previous value so that you can do things like

```r
old_opts <- options("a" = 1, "b" = 2)
on.exit(options(old_opts))
```

I think I'm partial to it returning the previous value, even if it's a bit uncharacteristic of a `fn<-` method.
